### PR TITLE
Switch coding standards to PSR-2

### PR DESCRIPTION
**Pull request by clash82**

### CODE REVIEW

**Comment by andrerom** [comment]
+1, FYI I have turned off Travis for now here,  _not high priority for this repo, just wanted to mention it;_ please plan to add some unit test in the future  and `.travis.yml` file so I can re enable it (cc @SylvainGuittard )

**Comment by clash82** [comment]
OK and thank you. I'm planning to add some tests with next release.

**Comment by michalpipa** [comment]
+1

**Comment by clash82** [comment]
ping @andrerom ;)

**Comment by clash82** [comment]
Thank you :)

**Pull request merged**
