### PR TITLE
Remove Assetic dependency

### PR DESCRIPTION
**Pull request by nicodmf**
#20

### CODE REVIEW

**Comment by kamilmusial** [comment]
zrzut ekranu 2017-07-07 o 09 13 37
Markdown seems broken. Can you test it?

**Comment by nicodmf** [comment]
Yes i don't understand why, i shall make the change not online

**Comment by nicodmf** [comment]
It's done

**Comment by damianz5** [comment]
[This](https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/pull/21/files#diff-04c6e90faac2675aa89e2176d2eec7d8R29) also can be moved to `optional` section

**Comment by nicodmf** [comment]
Done

**Comment by SylvainGuittard** [comment]
@damianz5 what is the issue with @ezrobot?

**Comment by andrerom** [comment]
@SylvainGuittard maybe check with @vidarl

**Comment by vidarl** [comment]
Outdated php cs fix config
Suggested fix : https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/pull/23

**Comment by SylvainGuittard** [comment]
#23 merged to master
Thanks @vidarl

**Comment by SylvainGuittard** [comment]
Thanks @nicodmf for the contribution

**Pull request merged**
