### PR TITLE
Add possibility send other params in override template

### PR DESCRIPTION
**Pull request by anijra**

### CODE REVIEW

**Review by SylvainGuittard — APPROVED** [review]

**Comment by clash82** [comment]
Hi @anijra, could you please explain a bit what are you trying to achieve with this request? What is your real life use case?

**Comment by SylvainGuittard** [comment]
Happy to see that you are back @clash82 (master of EzSystemsPrivacyCookieBundle) ;)

**Comment by clash82** [comment]
@SylvainGuittard It's my baby, I can't leave it just like that ;-)

**Review by damianz5 — APPROVED** [review]

**Comment by anijra** [comment]
Hi @clash82 i use 'otherParams' in my override template to display an additional text coming from an external source (content eZ) using detailed/collapsed html block privacy cookie

for example cookie used http://www.lac.ox.ac.uk/privacy-and-cookies

**Comment by clash82** [comment]
@anijra thanks for clarification :-) I think there are other less or more better ways to achieve this without modifyng bundle, but I'm not against this change.  I would suggest only to rename `otherParams` to `extraParams`.

**Comment by SylvainGuittard** [comment]
Thanks @anijra for this contribution.
@clash82 thanks again for your help. You're are more than welcome to help us "to raise your baby" ;)

**Pull request merged**
